### ISSUE TITLE
Big problem

### ISSUE THREAD

**Issue by EncodeTheCode** [MathiasVP/CS#4]
The game does not load... even with full file permissions enabled.

**Comment by MathiasVP** [comment]
I haven't touched the code in many years, so I don't actually know if and how the browser APIs have changed. Have you provided the correct data files? What does the chrome console say?

**Comment by MathiasVP** [comment]
I just checked myself and the game loads perfectly given the correct files, plus an additional argument to Chrome :)

- Run Chrome with the `--allow-file-access-from-files` flag instead of -`-disable-web-security`
- Open `game.html` and start the Chrome console. You will see complaints about missing various data files. Start filling these in by copying them from your local copy of CS 1.6.

Note that you shouldn't just randomly start downloading the files off the internet. Some of the files you'll find on the first couple of hits on Google will be modified versions of some of the model files, which won't be parsed successfully. In the end the files you need to get all up and running is:

- data/maps/cs_assault.bsp
- data/models/v_m3.mdl
- data/player/arctic/arctic.mdl
- data/sounds/weapons/m3-1.wav
- data/sprites/weapon_m3.txt

All of which can be found in your local installation of CS 1.6 from Steam.

**Comment by EncodeTheCode** [comment]
I'm referring to it doesnt't load out of the box without having to install npm or whatever it's called. :)
It'd be much cooler if it was stand alone.
